"""api_key and vehicle_code_mapping

Revision ID: 31d08ac51c74
Revises: d4e5f6a7b8c9
Create Date: 2026-08-11 11:12:24.570481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d08ac51c74'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key_prefix'), ['key_prefix'], unique=False)

    op.create_table('vehicle_code_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('car2_code', sa.String(length=64), nullable=False),
    sa.Column('car1_code', sa.String(length=64), nullable=False),
    sa.Column('car2_name', sa.String(length=256), nullable=True),
    sa.Column('car1_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'car2_code', name='uq_vcm_level_car2')
    )
    with op.batch_alter_table('vehicle_code_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_code_mapping_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_code_mapping_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_code_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_code_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_vehicle_code_mapping_level'))

    op.drop_table('vehicle_code_mapping')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_key_prefix'))

    op.drop_table('api_key')
    # ### end Alembic commands ###
