"""initial schema

Revision ID: 3702cedbc59f
Revises: 
Create Date: 2026-07-17 21:05:51.193587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3702cedbc59f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.String(length=20), nullable=True),
    sa.Column('auction_date', sa.String(length=20), nullable=True),
    sa.Column('maker', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('car_name', sa.String(length=255), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('car_km', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('imported', sa.String(length=10), nullable=True),
    sa.Column('start_price', sa.Integer(), nullable=True),
    sa.Column('hope_price', sa.Integer(), nullable=True),
    sa.Column('hammer_price', sa.Integer(), nullable=True),
    sa.Column('accident_detail', sa.String(length=100), nullable=True),
    sa.Column('xx_exchange', sa.Text(), nullable=True),
    sa.Column('w_panel', sa.Text(), nullable=True),
    sa.Column('is_accident_free', sa.Boolean(), nullable=True),
    sa.Column('car_code', sa.String(length=64), nullable=True),
    sa.Column('km_bin', sa.String(length=40), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auction_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_record_car_code'), ['car_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_record_week_no'), ['week_no'], unique=False)

    op.create_table('listing',
    sa.Column('car_no', sa.String(length=50), nullable=False),
    sa.Column('car_name', sa.String(length=150), nullable=True),
    sa.Column('maker_no', sa.Integer(), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('car_km', sa.Integer(), nullable=True),
    sa.Column('car_amount_sale', sa.Integer(), nullable=True),
    sa.Column('sido', sa.String(length=50), nullable=True),
    sa.Column('kind_name', sa.String(length=100), nullable=True),
    sa.Column('imported', sa.String(length=5), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('car_no')
    )
    op.create_table('llm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('market_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_code', sa.String(length=64), nullable=True),
    sa.Column('maker', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('car_name', sa.String(length=255), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('imported', sa.String(length=10), nullable=True),
    sa.Column('is_accident_free', sa.Boolean(), nullable=True),
    sa.Column('km_bin', sa.String(length=40), nullable=True),
    sa.Column('start_avg', sa.Float(), nullable=True),
    sa.Column('hammer_avg', sa.Float(), nullable=True),
    sa.Column('mom_pct', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('week_no', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_summary_car_code'), ['car_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_summary_car_year'), ['car_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_summary_maker'), ['maker'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_summary_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_summary_week_no'), ['week_no'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'lang', name='uq_trans')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)

    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('week_no', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rows_ok', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle_price_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=255), nullable=True),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('imported', sa.String(length=10), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_price_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_price_table_car_name'), ['car_name'], unique=False)

    op.create_table('gemini_report_cache',
    sa.Column('car_no', sa.String(length=50), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_no'], ['listing.car_no'], ),
    sa.PrimaryKeyConstraint('car_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemini_report_cache')
    with op.batch_alter_table('vehicle_price_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_price_table_car_name'))

    op.drop_table('vehicle_price_table')
    op.drop_table('user')
    op.drop_table('upload_history')
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))

    op.drop_table('translation_cache')
    op.drop_table('sync_log')
    with op.batch_alter_table('market_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_summary_week_no'))
        batch_op.drop_index(batch_op.f('ix_market_summary_model_name'))
        batch_op.drop_index(batch_op.f('ix_market_summary_maker'))
        batch_op.drop_index(batch_op.f('ix_market_summary_car_year'))
        batch_op.drop_index(batch_op.f('ix_market_summary_car_code'))

    op.drop_table('market_summary')
    op.drop_table('llm_config')
    op.drop_table('listing')
    with op.batch_alter_table('auction_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_record_week_no'))
        batch_op.drop_index(batch_op.f('ix_auction_record_car_code'))

    op.drop_table('auction_record')
    # ### end Alembic commands ###
