"""analysis_logic

Revision ID: 508eee195e17
Revises: 31d08ac51c74
Create Date: 2026-08-11 17:43:04.601912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508eee195e17'
down_revision = '31d08ac51c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_logic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_logic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_logic_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_logic_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_logic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_logic_code'))
        batch_op.drop_index(batch_op.f('ix_analysis_logic_category'))

    op.drop_table('analysis_logic')
    # ### end Alembic commands ###
