"""llm_config_api_key

Revision ID: 5728eb86808e
Revises: 3702cedbc59f
Create Date: 2026-07-17 21:28:55.701824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5728eb86808e'
down_revision = '3702cedbc59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_config', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
